// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "cart_types.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fastTree
void fastTree(arma::mat data);
RcppExport SEXP _cart_fastTree(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    fastTree(data);
    return R_NilValue;
END_RCPP
}
// f
void f(arma::mat data, bool code);
RcppExport SEXP _cart_f(SEXP dataSEXP, SEXP codeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< bool >::type code(codeSEXP);
    f(data, code);
    return R_NilValue;
END_RCPP
}
// g
void g(arma::mat data, bool code);
RcppExport SEXP _cart_g(SEXP dataSEXP, SEXP codeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< bool >::type code(codeSEXP);
    g(data, code);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cart_fastTree", (DL_FUNC) &_cart_fastTree, 1},
    {"_cart_f", (DL_FUNC) &_cart_f, 2},
    {"_cart_g", (DL_FUNC) &_cart_g, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_cart(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
