# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastTree <- function(data, code) {
    invisible(.Call(`_cart_fastTree`, data, code))
}

testPartitionMap <- function(data, code) {
    .Call(`_cart_testPartitionMap`, data, code)
}

test <- function(data, code) {
    .Call(`_cart_test`, data, code)
}

sortOnFeatureSub <- function(data, rowvec, d) {
    .Call(`_cart_sortOnFeatureSub`, data, rowvec, d)
}

sortOnFeature <- function(data, d) {
    .Call(`_cart_sortOnFeature`, data, d)
}

sortDataOnFeature <- function(data, d) {
    .Call(`_cart_sortDataOnFeature`, data, d)
}

timeTree <- function(data, code) {
    invisible(.Call(`_cart_timeTree`, data, code))
}

testBuildTree <- function(z, rows) {
    .Call(`_cart_testBuildTree`, z, rows)
}

sse <- function(x, n, xbar) {
    .Call(`_cart_sse`, x, n, xbar)
}

