# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function(data) {
    .Call(`_cart_test`, data)
}

testBuildTree <- function(z, rows) {
    .Call(`_cart_testBuildTree`, z, rows)
}

sse <- function(x, n, xbar) {
    .Call(`_cart_sse`, x, n, xbar)
}

