# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastTree <- function(data) {
    invisible(.Call(`_cart_fastTree`, data))
}

f <- function(data, code) {
    invisible(.Call(`_cart_f`, data, code))
}

g <- function(data, code) {
    invisible(.Call(`_cart_g`, data, code))
}

